import type { HoleDefinition } from "./types";

/**
 * Three hand-designed holes. Coordinates are local to each hole (every hole
 * is centered on its own origin — Course fully remounts per hole via a
 * React `key`, so there is no need to lay them out in a shared world space).
 */
export const HOLES: HoleDefinition[] = [
  {
    id: 1,
    name: "Rozcvička",
    description: "Krátka a priama jamka na zohriatie nohy — jedna piesková prekážka stráži green.",
    par: 3,
    tee: [0, -40],
    pin: [0, 40],
    startYaw: 0,
    bounds: { width: 44, depth: 96 },
    baseHeight: 0,
    cupRadius: 0.4,
    terrain: [
      { kind: "noise", amplitude: 0.025, frequency: 0.08, seed: 11 },
      { kind: "bump", center: [3, -2], radiusX: 14, radiusZ: 16, height: 1.4 },
      { kind: "bump", center: [-6, 25], radiusX: 8, radiusZ: 8, height: -0.4 },
      { kind: "slope", dir: [0, 1], strength: 0.006 },
    ],
    surfaceZones: [
      { surface: "fairway", priority: 1, shape: { type: "rect", center: [0, 0], size: [16, 84], rotation: 0 } },
      { surface: "tee", priority: 3, shape: { type: "circle", center: [0, -40], radius: 3 } },
      { surface: "green", priority: 3, shape: { type: "circle", center: [0, 40], radius: 9 } },
      {
        surface: "sand",
        priority: 4,
        shape: { type: "ellipse", center: [7, 34], radiusX: 4, radiusZ: 3, rotation: 0.3 },
      },
    ],
    waterHazards: [],
    obstacles: [
      { type: "pineTree", position: [-14, -10], scale: 1.1, rotation: 0.4 },
      { type: "roundTree", position: [15, 5], scale: 1.0, rotation: 1.2 },
      { type: "pineTree", position: [-16, 20], scale: 1.3, rotation: 2.1 },
      { type: "rock", position: [10, 30], scale: 0.8, rotation: 0.6 },
      { type: "rock", position: [-9, 33], scale: 0.6, rotation: 0.9 },
      { type: "bush", position: [12, -20], scale: 1.0, rotation: 0.2 },
      { type: "bush", position: [-13, 8], scale: 0.9, rotation: 1.4 },
    ],
  },
  {
    id: 2,
    name: "Zákruta pri jazere",
    description: "Dogleg doprava okolo kopca a jazera — buď hraj bezpečne, alebo skús skratku cez vodu.",
    par: 4,
    tee: [-18, -52],
    pin: [20, 50],
    startYaw: 0.42,
    bounds: { width: 70, depth: 120 },
    baseHeight: 0,
    cupRadius: 0.4,
    terrain: [
      { kind: "noise", amplitude: 0.03, frequency: 0.06, seed: 42 },
      { kind: "bump", center: [-2, 4], radiusX: 20, radiusZ: 22, height: 5.5 },
      { kind: "bump", center: [6, -6], radiusX: 16, radiusZ: 14, height: -2.2 },
      { kind: "slope", dir: [1, 1], strength: 0.005 },
    ],
    surfaceZones: [
      { surface: "fairway", priority: 1, shape: { type: "rect", center: [-10, -30], size: [16, 50], rotation: -0.3 } },
      { surface: "fairway", priority: 1, shape: { type: "rect", center: [12, 22], size: [20, 55], rotation: 0.35 } },
      { surface: "tee", priority: 3, shape: { type: "circle", center: [-18, -52], radius: 3 } },
      { surface: "green", priority: 3, shape: { type: "circle", center: [20, 50], radius: 10 } },
      {
        surface: "sand",
        priority: 4,
        shape: { type: "ellipse", center: [8, 38], radiusX: 5, radiusZ: 3.5, rotation: -0.2 },
      },
    ],
    waterHazards: [
      { shape: { type: "ellipse", center: [6, -6], radiusX: 15, radiusZ: 13, rotation: 0 }, level: -1.6 },
    ],
    obstacles: [
      { type: "pineTree", position: [-2, -2], scale: 1.6, rotation: 0.2 },
      { type: "pineTree", position: [-20, -25], scale: 1.2, rotation: 1.0 },
      { type: "pineTree", position: [-22, -40], scale: 1.1, rotation: 2.0 },
      { type: "roundTree", position: [22, -30], scale: 1.0, rotation: 0.5 },
      { type: "reeds", position: [-6, -16], scale: 1.0, rotation: 0 },
      { type: "reeds", position: [18, -10], scale: 1.0, rotation: 0.8 },
      { type: "rock", position: [24, 10], scale: 1.0, rotation: 0.3 },
      { type: "rock", position: [26, 14], scale: 0.7, rotation: 0.4 },
      { type: "roundTree", position: [26, 30], scale: 1.1, rotation: 1.5 },
      { type: "bush", position: [14, 42], scale: 0.9, rotation: 0.6 },
      { type: "postMarker", position: [-4, -14], scale: 1, rotation: 0 },
    ],
  },
  {
    id: 3,
    name: "Veľký kopec",
    description: "Najdlhšia jamka: úzka fairway pomedzi skaly a kopce, jazero stráži green.",
    par: 5,
    tee: [0, -66],
    pin: [-6, 68],
    startYaw: 0.06,
    bounds: { width: 60, depth: 150 },
    baseHeight: 0,
    cupRadius: 0.45,
    terrain: [
      { kind: "noise", amplitude: 0.035, frequency: 0.05, seed: 7 },
      { kind: "bump", center: [0, -66], radiusX: 10, radiusZ: 10, height: 2.0 },
      { kind: "ridge", from: [-8, -30], to: [6, 10], width: 14, height: 4.5 },
      { kind: "bump", center: [14, 30], radiusX: 14, radiusZ: 18, height: 3.2 },
      { kind: "bump", center: [6, 60], radiusX: 16, radiusZ: 14, height: -2.4 },
      { kind: "slope", dir: [0, 1], strength: -0.003 },
    ],
    surfaceZones: [
      { surface: "fairway", priority: 1, shape: { type: "rect", center: [-2, -45], size: [14, 42], rotation: -0.15 } },
      { surface: "fairway", priority: 1, shape: { type: "rect", center: [-10, -5], size: [14, 50], rotation: -0.35 } },
      { surface: "fairway", priority: 1, shape: { type: "rect", center: [-2, 35], size: [16, 48], rotation: 0.25 } },
      { surface: "fairway", priority: 1, shape: { type: "rect", center: [-6, 60], size: [16, 26], rotation: 0.1 } },
      { surface: "tee", priority: 3, shape: { type: "circle", center: [0, -66], radius: 3.5 } },
      { surface: "green", priority: 3, shape: { type: "circle", center: [-6, 68], radius: 10 } },
      {
        surface: "sand",
        priority: 4,
        shape: { type: "ellipse", center: [-16, 64], radiusX: 4, radiusZ: 3, rotation: 0.3 },
      },
    ],
    waterHazards: [
      { shape: { type: "ellipse", center: [6, 60], radiusX: 15, radiusZ: 13, rotation: 0 }, level: -1.8 },
    ],
    obstacles: [
      { type: "rock", position: [-14, -32], scale: 1.1, rotation: 0.2 },
      { type: "rock", position: [8, -20], scale: 0.9, rotation: 0.7 },
      { type: "rockCluster", position: [12, -2], scale: 1.3, rotation: 0.4 },
      { type: "rockCluster", position: [-18, -8], scale: 1.1, rotation: 1.1 },
      { type: "pineTree", position: [16, 22], scale: 1.4, rotation: 0.3 },
      { type: "pineTree", position: [20, 34], scale: 1.2, rotation: 1.8 },
      { type: "pineTree", position: [-22, 10], scale: 1.3, rotation: 2.4 },
      { type: "roundTree", position: [-20, 40], scale: 1.1, rotation: 0.9 },
      { type: "rock", position: [-12, 52], scale: 0.8, rotation: 0.5 },
      { type: "reeds", position: [-6, 54], scale: 1.0, rotation: 0.2 },
      { type: "reeds", position: [14, 66], scale: 1.0, rotation: 1.0 },
      { type: "bush", position: [4, -50], scale: 1.0, rotation: 0.6 },
    ],
  },
];
